package main

import (
	"flag"
	"fmt"
	"os"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	var flags flag.FlagSet

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(plugin *protogen.Plugin) error {
		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}
			fmt.Fprintf(os.Stderr, "%s\n", f.GeneratedFilenamePrefix)
			filename := fmt.Sprintf("%s.pb.goor.go", f.GeneratedFilenamePrefix)
			g := plugin.NewGeneratedFile(filename, f.GoImportPath)
			g.P("// Code generated by protoc-gen-goor. DO NOT EDIT.")
			g.P("package ", f.GoPackageName)
			if err := GenerateGrain(g, f); err != nil {
				panic(err)
			}
		}

		return nil
	})
}
