// Code generated by sqlc. DO NOT EDIT.

package internal

import (
	"database/sql"
)

type Observer struct {
	ID             int64
	OwnerGrain     string
	ObservableName string
	ObserverGrain  string
	Expires        sql.NullTime
}

type ObserverValue struct {
	ID          int64
	ObserversID int64
	Val         []byte
}
