// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	descriptor "github.com/jaym/go-orleans/grain/descriptor"
	mock "github.com/stretchr/testify/mock"
)

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

// Lookup provides a mock function with given fields: grainType
func (_m *Registrar) Lookup(grainType string) (descriptor.ActivatorConfig, error) {
	ret := _m.Called(grainType)

	var r0 descriptor.ActivatorConfig
	if rf, ok := ret.Get(0).(func(string) descriptor.ActivatorConfig); ok {
		r0 = rf(grainType)
	} else {
		r0 = ret.Get(0).(descriptor.ActivatorConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(grainType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: grainType, activatorFunc, opts
func (_m *Registrar) Register(grainType string, activatorFunc descriptor.ActivatorFunc, opts ...descriptor.ActivatorOpt) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, grainType, activatorFunc)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

type mockConstructorTestingTNewRegistrar interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistrar creates a new instance of Registrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistrar(t mockConstructorTestingTNewRegistrar) *Registrar {
	mock := &Registrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
