// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	descriptor "github.com/jaym/go-orleans/grain/descriptor"
	mock "github.com/stretchr/testify/mock"
)

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

// LookupV2 provides a mock function with given fields: grainType
func (_m *Registrar) LookupV2(grainType string) (descriptor.ActivatorFunc, error) {
	ret := _m.Called(grainType)

	var r0 descriptor.ActivatorFunc
	if rf, ok := ret.Get(0).(func(string) descriptor.ActivatorFunc); ok {
		r0 = rf(grainType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(descriptor.ActivatorFunc)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(grainType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterV2 provides a mock function with given fields: grainType, activatorFunc
func (_m *Registrar) RegisterV2(grainType string, activatorFunc descriptor.ActivatorFunc) {
	_m.Called(grainType, activatorFunc)
}

type mockConstructorTestingTNewRegistrar interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistrar creates a new instance of Registrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistrar(t mockConstructorTestingTNewRegistrar) *Registrar {
	mock := &Registrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
