// Code generated by sqlc. DO NOT EDIT.

package internal

import (
	"database/sql"
)

type Grain struct {
	ID        int64
	NodeID    int64
	NodeName  string
	GrainType string
	GrainID   string
}

type Node struct {
	ID          int64
	Name        string
	LastCheckin sql.NullTime
}
